### ISSUE TITLE
newick tree is not generating for CRC data

### ISSUE THREAD

**Issue by CSTE7007** [raphael-group/ConDoR#2]
I ran the code for example data and that produced four files as below:
 ```
data/sample/overview_B.csv
data/sample/overview_tree.dot
data/sample/overview_tree.newick
data/sample/overview_tree_without_cells.dot
```
where `overview_tree.newick` file had values inside.

But when I ran the code for `data/CRC` folder as follow:
`python src/condor.py -i data/CRC/input/character_matrix.csv -a 0.0018 -b 0.001 -k 1 -r data/CRC/input/total_readcounts.csv -v data/CRC/input/alt_readcounts.csv -o data/CRC/CRC`
it generated 
```
        data/CRC/CRC_B.csv
        data/CRC/CRC_tree.dot
        data/CRC/CRC_tree.newick
        data/CRC/CRC_tree_without_cells.dot
```
But the `data/CRC/CRC_tree.newick` file was with empty value as` ();`

**Comment by sashitt2** [comment]
Thank you for your interest in using ConDoR. I have now fixed the code so it should output the newick file correctly (before this change, the cell name had to start with 's' for the newick file to be generated correctly). I have tested that the code works now, but please let me know if the problem persists.
