### ISSUE TITLE
Gurobipy question

### ISSUE THREAD

**Issue by murphycj** [raphael-group/ConDoR#4]
Is a license to Gurobi required? Or will ConDoR be able to run within the restrictions of the free "limited license"?

If a license is required, is it feasible to make ConDoR work without the Gurobi dependency?

Thanks!

**Comment by sashitt2** [comment]
Unfortunately, at the moment the gurobi license is required to use ConDoR. The limited license will only allow you to solve small instances.

I am working on an extension that will not require such licenses which will be out in the next few months.
