### ISSUE TITLE
Running speed

### ISSUE THREAD

**Issue by Yakun-Pang** [raphael-group/ConDoR#6]
Hi,
Thank you for developing these excellent tools for single-cell phylogenetic trees.
It works well for me when I am using around 30 SNPs. However, it takes forever to finish after I add the LOH sites to my SNP list to distinguish the cells that lose different chromatin copies.  The dataset now has 114 cells and 145 SNP sites. I have had it running on my computer for a week now, but it is still running, and I have no idea how much time is left.
I would like to run it with HPC, but the longest time I can request for a run is only 7 days. Do you have any suggestions about how I can accelerate it? How much memory space and CPU should I request?
Thank you!

**Comment by sashitt2** [comment]
It is possible that the code is stuck at a solution very close to optimality. If you are ok with a slightly suboptimal solution, I would recommend increasing the optimality tolerance in line 286 of the solveConstrainedDollo.py, i.e. replace 1e-6 with a higher value such as 0.05 or 0.1 in the following line:

`model.setParam(gp.GRB.Param.OptimalityTol, 1e-6)`

Here is a description of this parameter which might be helpful -- https://www.gurobi.com/documentation/current/refman/optimalitytol.html
