### ISSUE TITLE
ValueError: cannot reshape array of size 1 

### ISSUE THREAD

**Issue by andreyurch** [raphael-group/ConDoR#8]
python src/condor.py -i  data/sample/overview_character_matrix.csv -a 0.0018 -b 0.001 -k 1 -r data/sample/overview_read_count.csv -v data/sample/overview_variant_count.csv -o data/sample/overview
n = 25, m = 25, p = 5
Set parameter Threads to value 1
Set parameter Method to value 4
Set parameter IntFeasTol to value 1e-06
Gurobi Optimizer version 11.0.2 build v11.0.2rc0 (mac64[x86] - Darwin 22.6.0 22G436)

CPU model: Intel(R) Core(TM) i5-7500 CPU @ 3.40GHz
Thread count: 4 physical cores, 4 logical processors, using up to 1 threads

Optimize a model with 40350 rows, 6125 columns and 125725 nonzeros
Model fingerprint: 0x129da912
Variable types: 5375 continuous, 750 integer (750 binary)
Coefficient statistics:
  Matrix range     [1e+00, 1e+00]
  Objective range  [9e-03, 4e+01]
  Bounds range     [1e+00, 1e+00]
  RHS range        [1e+00, 1e+01]
Found heuristic solution: objective -0.0000000
Presolve removed 975 rows and 925 columns
Presolve time: 0.25s
Presolved: 39375 rows, 5200 columns, 123750 nonzeros
Variable types: 2025 continuous, 3175 integer (3175 binary)
Root relaxation presolved: 5200 rows, 44575 columns, 128950 nonzeros

Root relaxation: objective 6.706072e+02, 5993 iterations, 0.31 seconds (0.37 work units)

    Nodes    |    Current Node    |     Objective Bounds      |     Work
 Expl Unexpl |  Obj  Depth IntInf | Incumbent    BestBd   Gap | It/Node Time

     0     0  670.60722    0  126   -0.00000  670.60722      -     -    0s
H    0     0                     530.7003379  670.60722  26.4%     -    0s
H    0     0                     553.5691395  670.60722  21.1%     -    0s
     0     0  669.68713    0  100  553.56914  669.68713  21.0%     -    1s
H    0     0                     664.8979464  669.15090  0.64%     -    1s
H    0     0                     666.2980959  669.15090  0.43%     -    1s
H    0     0                     667.7068849  669.15090  0.22%     -    1s
*    0     0               0     669.1509039  669.15090  0.00%     -    1s

Cutting planes:
  Gomory: 7
  Cover: 2
  MIR: 21
  Flow cover: 10
  Mod-K: 1
  RLT: 11

Explored 1 nodes (7346 simplex iterations) in 1.64 seconds (1.40 work units)
Thread count was 1 (of 4 available processors)

Solution count 7: 669.151 667.707 666.298 ... -0

Optimal solution found (tolerance 1.00e-04)
Best objective 6.691509038654e+02, best bound 6.691509038654e+02, gap 0.0000%
507, 57, 669.1509038654461
Traceback (most recent call last):
  File "src/condor.py", line 98, in <module>
    main(args)
  File "src/condor.py", line 68, in main
    solver.solveSetInclusion()
  File "/Users/testaccount/Documents/app/ConDoR/src/solveConstrainedDollo.py", line 303, in solveSetInclusion
    solb = np.rint(np.reshape(model.getAttr('x', b).values(), (ncells, nmutations)))
  File "<__array_function__ internals>", line 180, in reshape
  File "/Users/testaccount/mosaic/lib/python3.8/site-packages/numpy/core/fromnumeric.py", line 298, in reshape
    return _wrapfunc(a, 'reshape', newshape, order=order)
  File "/Users/testaccount/mosaic/lib/python3.8/site-packages/numpy/core/fromnumeric.py", line 54, in _wrapfunc
    return _wrapit(obj, method, *args, **kwds)
  File "/Users/testaccount/mosaic/lib/python3.8/site-packages/numpy/core/fromnumeric.py", line 43, in _wrapit
    result = getattr(asarray(obj), method)(*args, **kwds)
ValueError: cannot reshape array of size 1 into shape (25,25)

**Comment by sashitt2** [comment]
Sorry for the delay and thank you for bringing this to my attention.

This error is now fixed. Please let me know if any problems persist.
